[env]
EDITOR = "zed-preview"

[tools]
node = "lts"
pnpm = "11"
go = "latest"
lua-language-server = "latest"
taplo = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:yaml-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:portless" = "latest"
python = "latest"

[settings]
experimental = true
